#
# This file is part of the CRUDlexUser package.
#
# (c) Philip Lehmann-Böhm <philip@philiplb.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

language: php
before_script:
    - mysql -e 'CREATE DATABASE crudTest;'
    - composer install --dev --prefer-source
script: vendor/bin/phpunit
php:
    - 5.4
    - 5.5
    - 5.6
after_script:
    - php vendor/bin/coveralls -v
